create database HospitalManagementSystem;

USE HospitalManagementSystem;

CREATE TABLE OutPatient (
	PATIENT_ID VARCHAR (25) PRIMARY KEY,
	PATIENT_NAME VARCHAR (25) NOT NULL,
	PHONE_NUMBER BIGINT NOT NULL,
	AGE INT,
	GENDER VARCHAR (50),
	MEDICAL_HISTORY VARCHAR (50),
	PREFFERED_SPECIALIST VARCHAR (50),
	MEDICINE_FEE DOUBLE,
	PATIENT_TYPE VARCHAR (50),
	REGISTRATION_FEES DOUBLE,
    UNIQUE(Patient_name, Phone_number)
);

CREATE TABLE InPatient (
	PATIENT_ID VARCHAR (25) PRIMARY KEY,
	PATIENT_NAME VARCHAR (25) NOT NULL,
	PHONE_NUMBER BIGINT NOT NULL,
	AGE INT,
	GENDER VARCHAR (50),
	MEDICAL_HISTORY VARCHAR (50),
	PREFFERED_SPECIALIST VARCHAR (50),
	MEDICINE_FEE DOUBLE,
	PATIENT_TYPE VARCHAR (50),
	ADMISSION_FEES DOUBLE,
	TREATMENT VARCHAR (50),
	ROOM_TYPE VARCHAR (50),
	WANT_FOOD VARCHAR (50),
    UNIQUE(Patient_name, Phone_number)
);

CREATE TABLE Doctor (
	DOCTOR_ID VARCHAR (25) PRIMARY KEY,
	DOCTOR_NAME VARCHAR (25),
	DOCTOR_FEE DOUBLE,
	SPECIALIZATION VARCHAR (25),
	AVAILABLE_DATE DATE,
	AVAILABLE_TIME TIME
);

CREATE TABLE Appointment (
	APPOINTMENT_ID VARCHAR (25) UNIQUE NOT NULL,
    PATIENT_ID VARCHAR (25) NOT NULL,
    DOCTOR_ID VARCHAR (25) NOT NULL,
    SPECIALIZATION VARCHAR (25),
	APPOINTMENT_DATE DATE NOT NULL, 
	APPOINTMENT_TIME TIME NOT NULL,
	MODE_OF_APPOINTMENT VARCHAR (25),
    PRIMARY KEY(PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE),
    FOREIGN KEY(PATIENT_ID) REFERENCES outpatient(patient_id) on delete cascade,
	FOREIGN KEY(DOCTOR_ID) REFERENCES doctor(DOCTOR_ID) on delete cascade
);

CREATE TABLE Allocation (
	ALLOCATION_ID VARCHAR (25) PRIMARY KEY,
    PATIENT_ID VARCHAR (25),
    ROOM_NUMBER INT not null,
    NO_OF_DAYS_ADMITTED INT,
    ADMISSION_DATE DATE,
	DISCHARGE_DATE DATE,
	TREATMENT VARCHAR (25),
	ROOM_TYPE VARCHAR (25),
	WANT_FOOD VARCHAR (25),
    FOREIGN KEY(patient_id) REFERENCES InPatient(PATIENT_ID) on delete cascade,
    unique(patient_id, room_number)
);

CREATE TABLE Payment (
	PAYMENT_ID VARCHAR (25) PRIMARY KEY,
	INPATIENT_ID VARCHAR (25),
    OUTPATIENT_ID VARCHAR (25),
	PATIENT_NAME VARCHAR (25),
	PATIENT_TYPE VARCHAR (25),
	PAYMENT_DATE DATE,
	MODE_OF_PAYMENT VARCHAR (25),
	BILL_AMOUNT DOUBLE,
    FOREIGN KEY(InPatient_id) REFERENCES Inpatient(patient_id),
    FOREIGN KEY(OutPatient_id) REFERENCES Outpatient(patient_id)
);

SELECT * from doctor;
select * from payment;
select * from inpatient;
select * from outpatient;
select * from appointment;
SELECT * from allocation;

delete from allocation;
delete from appointment;
delete from payment;